[h2]Magia Práctica[/h2]
[b]Nivel I[/b]
[i]Alohomora[/i]
[i]Ferma[/i] 
[b]Nivel II[/b]
[i]Finite[/i] 
[i]Reparo[/i] 
[b]Nivel III[/b]
[i]Expelliarmus[/i] 
[b]Nivel IV[/b]
[b]Nivel V[/b]

[h2]Magia Combativa[/h2]
[b]Nivel I[/b]
[i]Tarantallegra[/i] 
[b]Nivel II[/b]
[i]Petrificus[/i] 
[b]Nivel III[/b]
[b]Nivel IV[/b]
[b]Nivel V[/b]

[h2]Magia Defensiva[/h2]
[b]Nivel I[/b]
[i]Palalingua[/i] 
[b]Nivel II[/b]
[i]Aloe[/i] 
[b]Nivel III[/b]
[b]Nivel IV[/b]
[b]Nivel V[/b]

[h2]Magia Transmutadora[/h2]
[b]Nivel I[/b]
[i]Reparifarge[/i] 
[b]Nivel II[/b]
[i]Tragacaracolores[/i] 
[b]Nivel III[/b]
[b]Nivel IV[/b]
[b]Nivel V[/b]

[h2]Magia Creadora[/h2]
[b]Nivel I[/b]
[i]Aguamenti[/i]
[b]Nivel II[/b]
[I]Aqua eructo [/i]
[b]Nivel III[/b]
[b]Nivel IV[/b]
[b]Nivel V[/b]

[h2]Magia Mental[/h2]
[b]Nivel I[/b]
[i]Potentis[/i]
[b]Nivel II[/b]
[I]Ataraxia[/i]
[b]Nivel III[/b]
[b]Nivel IV[/b]
[b]Nivel V[/b]